- bin/enact.js
- package.json
Handles the Node V8 cache for improved module load/execution time.
> ENYO-5142: Support v8-compile-cache for faster CLI runtime

- commands/create.js
When installing cli locally (e.g. via `enact create --locale test`), the babel polyfills can fail to be found if another package (e.g. `react`) has a dependency on a lower version of `core-js`.
Explicitly add the `core-js@2` dependency when using the `--local` option to ensure we have a compatible set of polyfills.
See: https://babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins
> ENYO-5632: Add core-js as a dev dependency for local installs

- commands/lint.js
- docs/building-apps.md
- docs/loading-existing-app.md
- docs/starting-a-new-app.md
Modifies `enact lint`. When js/jsx files exist, runs `eslint`. When ts/tsx files exist, and so does a `tslint.json`, and TSLint is installed locally or globally, run `tslint`.
> PLAT-71620: Implement optional Typescript linting support

- config/webpack.config.js
- package-lock.json
- package.json
Requires https://github.com/enactjs/postcss-resolution-independence/pull/1 and once that PR is merged, that package will be published to NPM and this PR will be updated accordingly.
Transition from using Less plugin for resolution independence to using PostCSS plugin.  Allows us to only process LESS files through the `less-loader`.
> PLAT-72999: Migrate resolution independence plugin to PostCSS

- config/jest/jest.config.js
Adds `ilib` alias support for tests; both for standalone `ilib` and `ilib/...` paths.
Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> ENYO-5772: Can't import aliased ilib path while testing

- config/jest/jest.config.js
Ensures out-out-project parent directories named 'coverage', 'build', and 'dist' don't accidentally cause all tests to be ignored.
> PLAT-73957: Travis failures after CLI 2.0.0 release

- README.md
- package-lock.json
- package.json
enact framework code should not ship any tests with `only` and error in our Travis CI. Here we add `esling-plugin-jest` dependency to support jest rule added in `eslint-config-enact` (https://github.com/enactjs/eslint-config-enact/pull/25)
Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>
> ENYO-5814: Add eslint-plugin-jest

- commands/link.js
Uses `npm config get prefix -g` to resolve global module path to allow for custom paths via npmrc configs.  Falls back to `global-modules` package.
Previously, the `enact link` process was relying on the `global-modules` library to determine where linked modules are globally installed (and then would link any available `@enact/*` ones that were also in the local `package.json`). However `global-modules` does not take into account when the global NPM prefix is set to something custom (can be done via multiple means). This update uses `npm config get prefix -g` to determine the final module path more thoroughly.
For example, on Jenkins we set `NPM_CONFIG_GLOBALCONFIG` env var to a local `/home/jenkins/workspace/job/.npmrc` value, which includes `PREFIX="/home/jenkins/workspace/job/npm"`. …
> PLAT-76550: Support custom NPM global prefix paths in CLI linking

- commands/serve.js
- config/webpack.config.js
Potential addition to https://github.com/enactjs/cli/pull/179
Alternative to the react-dev-utils TypeScript workaround which removes the MiniCssExtractPlugin usage in serving and whenever  `INLINE_STYLES` env var is set.  This is more in the `create-react-app` style, though may present issues with CSS order potentially (as CSS will be added to the dom in `<style>` tags dynamically, rather than everything collected into external `*.css` files and added as header stylesheet `<link>` tags).
> ENYO-5894: Change serve command to use inline CSS in style tags

- config/webpack.config.js
When env var `INLINE_STYLES` is set (such as during serving), disable stylesheet sourcemap generation.
This gets around an active issue with `style-loader` where when `sourceMaps` are enabled, the style loader attempts to add styles via Blob URLs rather than inline `<style>` tags. See https://github.com/webpack-contrib/style-loader/blob/81b4d188f373123d56c4e0ac2cd4554c8ed27a86/src/addStyles.js#L319 This can cause styles to load asynchronously affecting initial style-based metrics.
> ENYO-5932: Disable sourcemaps when using inline styles to avoid async blob stylesheets.

- commands/eject.js
- commands/license.js
- commands/transpile.js
- config/.babelrc.js
- config/babel.config.js
- config/jest/babelTransform.js
- config/jest/jest.config.js
- config/webpack.config.js
- docs/ejecting-apps.md
- package-lock.json
Fixes https://github.com/enactjs/cli/issues/182
* Renamed the `.babelrc.js` to `babel.config.js`, using the functional-export format (rather than basic object exports). This is the current preferred method. Updated any source file references to point new filepath.
* Makes the `babel.config.js` file standalone, explicitly set as the `configFile` in the Webpack `babel-loader`. As a result, the Babel `package.json` settings no longer need to be inject during eject process.
* Additionally fixed minor issues where Jest config files were not ejecting into `./config/` as they should have.
> ENYO-5928: Ejected apps fail load Babel correctly

- config/webpack.config.js
Resolve CLI serving compatibility with mock data for external tools.
Adds `./__mocks__` directory as a content base along with the current `./public` directory. Allows XHR requests to fallback for mock data files within `./__mocks__, while keeping out of public asset files.
Preferred alternative to https://github.com/enactjs/cli/pull/185
Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> PLAT-77105: Resolve CLI serving compatibility with custom Chrome extension

- README.md
- package-lock.json
- package.json
Requires https://github.com/enactjs/eslint-config-enact/pull/27 merged and published to NPM. At which point this PR can update the `eslint-config-enact` dependency.
Adds `eslint-plugin-react-hooks` dependency and will update `eslint-config-enact` package, which adds the `react-hooks/exhaustive-deps` warning and `react-hooks/rules-of-hooks` error rules.
> PLAT-76285: Enhanced React Hooks support in tooling

- config/corejs-proxy.js
Switch from polyfilling all needed features to polyfilling only stable features (not in draft state/stage 0-3).
> PLAT-78524: Narrow polyfill support to only stable features

- config/jest/jest.config.js
- config/webpack.config.js
Requires: https://github.com/enactjs/dev-utils/pull/44
Once that and https://github.com/enactjs/templates/pull/11 are merged, this PR can be updated for their new dependency releases.
Updates the Webpack and Jest configs for the new iLib location, along with temporary backwards-compatibility alias support so `@enact/i18n/ilib/...` imports/require statements still work (allowing app devs time to update).
> PLAT-80499: Transition to external iLib NPM module

- config/webpack.config.js
To be used with: https://github.com/enactjs/dev-utils/pull/42
Allows `undefined`/`null` values for resolution independence settings to allow default options to be used. However, still guard against an explicit `false`value as a method of disabling use of the POSTCSS plugin.
> PLAT-81105: Undetermined RI value can result in Infinity rem values

- config/babel.config.js
- config/polyfills.js
`es.typed-array.to-locale-string` calls `Int8Array.prototype.toLocaleString` as part of its implementation/checking. This breaks snapshotting, similar to how `Array.prototype.toLocaleString` would break snapshot.
If an implementation of `Int8Array.prototype.toLocaleString` exists, swap it with `Int8Array.prototype.toString` when `core-js@3` is being applied to ensure the native function doesn't execute and break the snapshot.
> ENYO-6134: Int8Array.prototype.toLocaleString invocation breaks snapshot

- commands/create.js
Adds support for `type` property on template generators for more accurate user-messages and potential future functionality filtering.
> ENYO-6133: Support template 'type' value for project creation feedback

- config/jest/setupTests.js
Adds `.animate()` support for tests that will fail due to https://github.com/enactjs/enact/pull/2475
Enact-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>
> Add animate support for tests

- config/jest/jest.config.js
Jest tests weren't loading project `.env` files like they should have been.  This PR adds dotenv loading to the Jest config to ensure all environment variables are present, like in our webpack builds.
> ENYO-6163: Jest tests fail to load dotenv files

- config/jest/jest.config.js
Redirect Jest requests for React library to use internal copy of React. This falls in-line with Enzyme usage.
> PLAT-97856: Figure out unit testing with hooks

- bin/enact.js
- commands/bootstrap.js
- commands/link.js
- index.js
Adds a new `enact bootstrap` command which will:
* If a `bootstrap` NPM script is set, runs `np, run bootstrap`
* Otherwise will run `npm install` followed by `enact link`. Will then additionally repeat the process on any sampler/samples in `./samples` root project directory.
As a side effect of the this change, I've added optional argument to `enact link` to target directories for linking (defaults to command working directory).
> PLAT-99524: Support simplified install/link process for theme ui repos

- CHANGELOG.md
- README.md
- docs/building-apps.md
- docs/starting-a-new-app.md
Adds information on our default browser targets and our core-js polyfill usage (and how browser feature are not polyfilled , only ECMAScript stable features)
> ENYO-6255: Added documentation on browser support and polyfills.

- commands/clean.js
Support cleaning `dist`/`build` directories within samples and ui/screenshot tests.
Adds support for `-a`/`--all` option to additionally delete `node_modules`.
> PLAT-100996: Update 'clean' command for additional locations

- commands/bootstrap.js
Since `../../` dependency for themes within their sampler will overwrite the theme's own production `node_modules`, the theme and theme `enact link` usage should occur last.
This PR changes the install/enact-link ordering accordingly. Additionally, it adds special detection for theme relative file dependency in samples to signify only devDependencies need to be install on the theme afterward. This reduces needless repetition and saves a small bit of time.
Also sets default loglevel of `error`, similar to `enact link`, as otherwise there would be a floor of output and much harder to read/understand. Similar to  `enact link`, the `--loglevel` and `--verbose` options exist to change this behavior as desired.
> ENYO-6422: Enact bootstrap overwrites any links in root theme package

- config/jest/jest.config.js
Some old code in our Jest setup was only handling Moonstone constants correctly (setting `ILIB_MOONSTONE_PATH`).
There was a bug for themed apps where we were setting `<THEME>` global instead of `ILIB_<THEME>_PATH` like we were meant to. This fixes that.
Additionally, to provide generalized support for in-theme usage the local resource resbundle path is added as `ILIB_<NAME>_PATH` to cover in-theme testing and some edge cases.
> PLAT-104442: Not correctly providing theme ResBundle constant for all themes

- config/webpack.config.js
- package-lock.json
- package.json
Requires https://github.com/enactjs/dev-utils/pull/57
Sets webpack's `resolve.symlinks` option to `false`, disabling path resolving for symlinks. This will preserve `node_modules/...` filepaths for modules linked in.
Once https://github.com/enactjs/dev-utils/pull/57 is merged and released, this PR will be updated for the new `@enact/dev-utils` version.
> PLAT-106664: Preserve unresolved symlinks path in output

- commands/serve.js
* Adds support for an optional app-side `./src/proxySetup.js` files which can hook in to the underlying webpack-dev-server for advanced proxy usage.
* This follows the `create-react-app` implementation format for optimal compatibility and future-handling.
* See https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually for examples of usage.
> PLAT-107662: Support expanded proxy settings

- config/webpack.config.js
Allows top level enact dependencies to be watched during `serve`.
The recent change of preserving symlink path (rather than resolving) altered `serve` to recognize linked Enact dependencies as falling under `./node_modules` tree, when in reality they resolve outside it to their linked location. This adds handling to avoid that and allow watchers to be attached to Enact dependency files.
Note: PR targetted to master for hotfix process. Once approved/merged, I'll do a 2.8.1 hotfix release and merge-back to develop.
> Allow watching Enact libraries, but not nested children dependencies.

- config/babel.config.js
*Applies `@babel/plugin-transform-runtime` only when not transpiling in standalone mode.
> PLAT-115954: Applies @babel/plugin-transform-runtime during standalone transpiling

- commands/create.js
- commands/template.js
- package-lock.json
- package.json
* Switches back to moonstone template for default.
* Detection and handling of dead/unreadable links in template userspace.
> PLAT-116110: Use moonstone as default template

- CHANGELOG.md
- commands/eject.js
- commands/serve.js
- fix 'eject --bare' doesn't work issue via checking '/scripts' folder exists or not
> PLAT-121346: Fix 'eject --bare` doesn't work

- CHANGELOG.md
- commands/serve.js
To resolve https://github.com/enactjs/cli/issues/228, changed `all` to `every` in `devServerConfig` function.
> PLAT-120112: Fixed https serve is not working

- commands/bootstrap.js
* Migrates the package lockfile override support from https://github.com/enactjs/enact-dev-dist/blob/master/node_binaries/enact-override.js into the existing `bootstrap` command as a private/undocumented feature for internal usage.
> PLAT-117141: Migrate shrinkwrap override support into CLI

- config/babel.config.js
- config/webpack.config.js
This PR adds support for the new JSX transform.
We could turn the feature off by setting `DISABLE_NEW_JSX_TRANSFORM` to `true` via `.env` file for `enact pack`.
We can't turn the rule off for `enact lint` though.
> PLAT-121645: Add support for new JSX Transform

- CHANGELOG.md
- config/webpack.config.js
For some TV apps, they had to use absolute path in the file system in url().
css-loader 3.x version did not handle the absolute path but it's now resolving(css-loader version 4.0.0 and above).
So, webpack throws a build error regarding not founding image path which is the absolute path of the file system.
To avoid the build failure, we disabled the resolving the absolute path of url().
> PLAT-141863: Skip resolving url() of absolute path

- CHANGELOG.md
- config/jest/setupTests.js
Fixed not reading mocks that already restored
* add undefined mock checking statements in `./config/jest/setupTests.js`
PLAT-141821
> PLAT-141821: Fixed not reading mocks that already restored

- CHANGELOG.md
- package.json
Some errors found while `enact pack`
> Error: Cannot find module ‘sanitize.css/page.css’
Require stack:
/usr/local/lib/node_modules/@enact/cli/node_modules/postcss-normalize/dist/index.cjs.js
./node_modules/@enact/ui/Scroller/UiScroller.module.css
Error: Cannot find module ‘sanitize.css/page.css’
Require stack:
/usr/local/lib/node_modules/@enact/cli/node_modules/postcss-normalize/dist/index.cjs.js
./node_modules/@enact/ui/Scroller/Scroller.module.css
Error: Cannot find module ‘sanitize.css/page.css’
Require stack:
/usr/local/lib/node_modules/@enact/cli/node_modules/postcss-normalize/dist/index.cjs.js
./node_modules/@enact/sandstone/Dropdown/Dropdown.module.css
Added `sanitize.css` module for supporting `postcss-normalize`
WRN-8051
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong …
> WRN-8051: Added `sanitize.css` module for supporting `postcss-normalize`

- config/custom-skin-template.ejs
This PR removes the script for adding skin name from the template used in --custom-skin pack option.
> WRN-10013: Remove script for adding skin name

- CHANGELOG.md
- config/webpack.config.js
From developers(Gitter), they want to use
`import SomeComponent from 'some-directory/component'`
rather than
`import SomeComponent from '../../../../../../../../../../some-directory/component'`
(https://webpack.kr/configuration/resolve/)
CRA also supports https://create-react-app.dev/docs/importing-a-component/#absolute-imports.
Add `additionalModulePaths` in enact option.
This will be used in webpack config to allow the user to supply additional paths to the resolve.modules section.
WRN-14724
> WRN-14724: Add `additionalModulePaths` to specify additional paths to search when resolving modules

- commands/pack.js
In this PR, we'd like to fix enact pack --verbose is not working.
webpack's ProgressPlugin is changed to check if `compiler` is an instance of `Compiler`.
Currently, dev-utils and cli have different webpack modules so ProgressPlugin created from dev-utils cannot work correctly.
To remedy this, I've changed to create PrgressPlugin from cli's webpack module.
> WRN-19252: Fix enact pack --verbose is not working

- npm-shrinkwrap.json
- package.json
In this PR, updated @enact/template-sandstone version to 1.5.0-alpha.2
> WRO-2887: update @enact/template-sandstone

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
When we run `enact test --watch`, an error shows like below on some node version.
```
Error: Failed to initialize watch plugin "../cli/node_modules/jest-watch-typeahead/build/file_name_plugin/plugin.js":
● Test suite failed to run
TypeError: Invalid host defined options
at requireOrImportModule (../cli/node_modules/jest-util/build/requireOrImportModule.js:65:55)
at watch (../cli/node_modules/@jest/core/build/watch.js:337:78)
at runWatch (../cli/node_modules/@jest/core/build/cli/index.js:359:29)
at _run10000 (../cli/node_modules/@jest/core/build/cli/index.js:311:13)
at async runCLI (../cli/node_modules/@jest/core/build/cli/index.js:173:3)
```
Down versioning `jest-watch-typeahead` to 0.6.5
WRO-3211
> WRO-3211: Fix `enact test --watch` is not working

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
in node 16 environment, devDependencies modules are not installed and cause error in `enact lint`, `enact serve`, etc.
```
Failed to compile.
Failed to load plugin 'react' declared in 'BaseConfig » /home/bongsok/.nvm/versions/node/v16.14.2/lib/node_modules/@enact/cli/node_modules/eslint-config-enact/index.js': Cannot find module 'eslint-plugin-react'
Require stack:
- /home/bongsok/.nvm/versions/node/v16.14.2/lib/node_modules/@enact/cli/config/__placeholder__.js
Referenced from: /home/bongsok/.nvm/versions/node/v16.14.2/lib/node_modules/@enact/cli/node_modules/eslint-config-enact/index.js
```
Move eslint modules into dependencies
WRO-3209
> WRO-3209: Fix `enact lint` is not working on node 16

- CHANGELOG.md
- config/webpack.config.js
`enact pack` fail on window 10
I'm seeing a file named `javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;` in `dist/` directory.
Fix html-webpack-plugin asset module support output
WRO-3110
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong ([taeyoung.hong@lge.com](mailto:taeyoung.hong@lge.com))
> WRO-3110: Fix `enact pack` fails on windows

- CHANGELOG.md
- config/jest/jest.config.js
`npm run test` is not working on windows environment
fix testMatch that supports windows os
WRO-3254
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong ([taeyoung.hong@lge.com](mailto:taeyoung.hong@lge.com))
> WRO-3254: Fix `enact test` can't find test files on windows

- CHANGELOG.md
- config/dotenv.js
enact pack failed when the app has `.env` file.
`dotenv-expand` module changed its module exports to object. So we need to get `expand` function by destructuring.
WRO-2087
> WRO-2087: Fixed build failure when .env file exists

- docs/building-apps.md
Enact CLI supports serve, pack, lint, and test for TypeScript apps with an optional way by installing the 'typescript' module globally.
Currently, even we do this, we have an error that says below.
> Failed to compile
.
[eslint] Failed to load plugin '@typescript-eslint' declared in 'BaseConfig » /home/taeyoung.hong/webos_build_server/WRO-521/cli/node_modules/eslint-config-enact/index.js#overrides[0]': Cannot find module 'typescript'
In this case, we can try to set `NODE_PATH` to point global, then the compile success.
> Creating a development build...
Compiled successfully.
NOTICE: This build contains debugging functionality and may run slower than in production mode.
.
3.15 MB         dist/main.js
218.48 kB …
> WRO-521: Update documentation for troubleshooting `cannot find module` error of globally installed module

- README.md
Enact CLI supports in-editor linting by installing the 'eslint-config-enact-proxy' module locally.
But for ease to use, we need to guide users more kindly and in detail.
Add a guide for installing eslint-config-enact-proxy
WRO-8722
> WRO-8722: Update in-editor linting guide

- CHANGELOG.md
- commands/serve.js
When we serve the app, the below warning is showing.
> (node:12686) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:12686) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
In webpack.js.org, these 2 options are deprecated in favor of the [devServer.setupMiddlewares](https://webpack.js.org/configuration/dev-server/#devserversetupmiddlewares) option.
(Check these links: …
> WRO-8972: Fix DeprecationWarning when `enact serve`

- CHANGELOG.md
- commands/pack.js
- docs/building-apps.md
sandstone supports custom skin features to let user easily override the colors of components via css variables.
Templates for the app need to load `custom_skin.css` which includes  a preset of colors.
To support this, we've added `--custom-skin` option to pack command to load `custom_skin.css` file from the template.
WRO-9005
> WRO-9005: Made `--custom-skin` public and added documentation

- CHANGELOG.md
- package.json
sandstone sample app qa-a11y build failed in Node 12 because optional chaining is not supported in Node 12.
We need to restore polyfills including 'optional chaining' in babel configs.
Update babel-preset-enact v0.1.1
WRP-9045
> WRP-9045: Update babel-preset-enact to fix isomorphic build fail on Node 12

- commands/pack.js
- config/webpack.config.js
To provide a way to turn off effects like animation from theme libraries, we need to add a build option.
Added a private build option `--no-animation` to turn off effects like animation or shadow.
It will define `ENACT_PACK_NO_ANIMATION` environment variable to turn the effects off conditionally from UI code.
WRP-11042, WRP-3555
> WRP-11042: Add a private build option to turn off effects like animation

- CHANGELOG.md
- bin/enact.js
- commands/eject.js
- package.json
`enact test --watch` option is not working with the latest `jest-watch-typeahead`
Removed `v8-compile-cache` dependency that did not work with ES modules and updated `jest-watch-typeahead` to its latest version.
Version 2.0.0 or later of `jest-watch-typeahead` dropped support for node 12 and 17. (https://github.com/jest-community/jest-watch-typeahead/blob/main/CHANGELOG.md)
When this PR is merged, node 14+ will be needed. …
> WRP-1058: Fixed enact test `--watch` option is not working with the latest `jest-watch-typeahead`

- CHANGELOG.md
- package.json
Enact-DCO-1.0-Signed-off-by: Stanca Pop [stanca.pop@lgepartner.com](mailto:stanca.pop@lgepartner.com)
With the Enact CLI 5.1.2 release there was a `@testing-library/dom` upgrade to version 9.0.0. This version has some breaking changes and caused unit tests to fail. `@testing-library/dom` package does not need to be explicitly set in package.json, as it comes as a peerDependency in `@testing-library/user-event`. 
We need to remove `@testing-library/dom` dependency from package.json and also upgrade `@testing-library/react` to major version ^14.0.0 (in the release noted, Features section, it mentions: "Bump …
> WRP-10063: Removed `@testing-library/dom` dependency and upgraded `@testing-library/react` to v^14.0.0

- CHANGELOG.md
- commands/pack.js
- config/webpack.config.js
- docs/building-apps.md
Some Enact apps are running as hosted web app. We need to support a way for the client can update hosted app files if the app is updated so that the client doesn't stay with the local cache.
One of the possible candidates is to use webpack hash config when pack.
(Caching description: https://webpack.kr/guides/caching)
(Set output description: https://webpack.js.org/configuration/output/#outputfilename, https://webpack.js.org/configuration/output/#outputchunkfilename)
- Add a pack option `--content-hash` to be used by the hosted web app
- If the option is true, add a unique hash value based on content to the …
> WRP-3673: Add a pack option `--content-hash` to support better caching

- CHANGELOG.md
- bin/enact.js
- commands/bootstrap.js
- commands/clean.js
- commands/create.js
- commands/eject.js
- commands/info.js
- commands/license.js
- commands/link.js
- commands/pack.js
- commands/serve.js
- commands/template.js
- commands/test.js
- commands/transpile.js
- npm-shrinkwrap.json
- package.json
`chalk` v5 and `strip-ansi` v7 have been released.
Those modules need to be updated to the latest node modules to fix security vulnerabilities and prevent malware.
Update `chalk` v5 and `strip-ansi` v7
- `chalk` and `strip-ansi` are now pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
`chalk`: https://github.com/chalk/chalk/releases/tag/v5.0.0
`strip-ansi`: https://github.com/chalk/strip-ansi/releases/tag/v7.0.0 …
> WRP-14327: Update chalk v5 and strip-ansi v7

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
`prettier` v3 and `eslint-plugin-prettier` v5 had been released.
This module needs to be updated to the latest node modules to fix security vulnerabilities and prevent malware.
Updates `prettier` related modules' version updates to the latest.
There are no breaking changes affecting this repository.
- https://prettier.io/blog/2023/07/05/3.0.0.html
- https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F
[//]: # (Related issues, …
> WRP-21844: Updates `prettier` related modules' major version updates

- commands/pack.js
- config/webpack.config.js
When an app used `React.Suspense` with `React.lazy` for the first screen and built the app with `snapshot` option, built result shows broken styles because some of CSS are not loaded well.
As I analyzed from WRQ-28908, when we lazy load some components, Webpack does code spliting. Because it's lazy loaded, which means we can load it on demand, the bundler doesn't need to add it to the main artifacts. And when it runs, these modules are loaded via Promise asynchronously.
This seems reasonable, but when we lazy load the components for the very first screen, it could cause the above problem when it goes along …
> WRR-3401: Added a build option to support Suspense with snapshot build

- commands/pack.js
- config/webpack.config.js
To reduce the size of built Enact app's CSS, added a private build option `--hash-classnames`.
Added a private build option `--hash-classnames`
Changed the webpack config to use [hash:base64] of css-loader's `localIdentName` property when the option is true.
WRR-8543
> WRR-8543: Added `--hash-classnames` for building hashed classnames

- config/webpack.config.js
- npm-shrinkwrap.json
- package.json
Remove the old postcss module
Remove the old postcss module
WRR-24215
> WRR-24215: Remove the old postcss module

- CHANGELOG.md
- config/eslintWebpackPluginConfig.js
Fix eslint always runs in strict mode during enact pack: https://github.com/enactjs/cli/issues/368
Instead of checking whether the value of `process.env.FRAMEWORK` exists or not, change it to check whether it is `true` or not.
WRR-29550
> WRR-29550: Fix eslint always runs in strict mode during enact pack
