enactjs/cli

package.json
=> ENYO-5208: Preserve React15 HTML comment nodes within prerenders

config/webpack.config.prod.js, package-lock.json, package.json
=> ENYO-5209: Limit Uglify optimizations to ECMA 5

config/karma.conf.js, config/webpack.config.dev.js, config/webpack.config.prod.js
Requires https://github.com/enactjs/dev-utils/pull/18
=> ENYO-5150: Support @moon-accent variable override

commands/pack.js
=> ENYO-5310: Add vebose logging support to Enact CLI pack

package.json
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Update to react plugin 7.9.1

config/karma.conf.js, config/webpack.config.dev.js, config/webpack.config.prod.js
=> ENYO-5357: Environment variable injection support

README.md, commands/create.js, commands/eject.js, commands/template.js, docs/building-apps.md, docs/developing-a-template.md, docs/ejecting-apps.md, docs/index.md, docs/installation.md, docs/isomorphic-support.md, docs/loading-existing-app.md, docs/serving-apps.md, docs/starting-a-new-app.md, docs/template-management.md, docs/testing-apps.md
=> ENYO-5290: Create docs for eject, environment, integration features.

commands/create.js, commands/link.js, docs/installation.md
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Update command help and docs

commands/pack.js, commands/serve.js, package-lock.json, package.json
Requires https://github.com/enactjs/dev-utils/pull/31
Alternate implementation to https://github.com/enactjs/cli/pull/144
=> PLAT-65802: Add meta flag support for overriding metadata at buildtime

commands/link.js
=> ENYO-5685: Incorrect error when linking Enact into non-Enact package.

config/karma.conf.js, config/webpack.config.dev.js, config/webpack.config.prod.js
=> ENYO-5698: Disable use of postcss-custom-properties plugin due to issue

commands/transpile.js
=> ENYO-5831: Option to disable CommonJS transpiling not being applied

commands/lint.js
Updates linting support for repo structures with embedded samplers and ui/screenshot tests.
=> PLAT-98768: Update ui-tests to be able to run from ui libraries

CHANGELOG.md, config/jest/jest.config.js, config/webpack.config.js
This PR fixes wrong glob patterns for the test files.
=> PLAT-138171: Fixed the glob patterns for test files

README.md, docs/building-apps.md, docs/developing-a-template.md, docs/isomorphic-support.md, docs/starting-a-new-app.md, docs/template-management.md, docs/testing-apps.md
This PR updates documentation.
=> PLAT-136430: Update documentation

CHANGELOG.md, commands/lint.js
Add ts/tsx conditions for linting typescript code.
Add ts/tsx conditions in commands/lint.js
PLAT-139238
=> PLAT-139238: Add ts/tsx conditions for linting Typescript files

CHANGELOG.md, config/webpack.config.js
Fixed title is not setting in index.html with enact pack.
* add a parameter in WebOSMetaPlugin constructor
PLAT-139651
=> PLAT-139651: Fixed not inserting title into the output HTML with enact pack

CHANGELOG.md, config/jest/jest.config.js
Fix the issue that cannot find userSetupFile
* Fix the typing error in userSetupFile variable in `./config/jest/jest.config.js`
PLAT-141820
=> PLAT-141820: Fix the issue that cannot find userSetupFile

docs/building-apps.md, docs/installation.md
In this PR, we'd like to update documentation.
=> WRO-739: Update docs

CHANGELOG.md, npm-shrinkwrap.json, package.json
Update @enact/template-sandstone 1.5.0-alpha.3
WRO-4074
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong [taeyoung.hong@lge.com](mailto:taeyoung.hong@lge.com)
=> WRO-4074: update @enact/template-sandstone

config/webpack.config.js, npm-shrinkwrap.json, package.json
We need to merge postcss-resolution-independence@1.1.0 into develop
There's an postcss version asynchronous between CLI's postcss version & postcss-resolution-independence
Update postcss-resolution-independence module
WRO-4243
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong ([taeyoung.hong@lge.com](mailto:taeyoung.hong@lge.com))
=> WRO-4243: Update postcss-resolution-independence

package.json
Need to update homepage information in the @enact/cli page of npmjs.com
Add 'homepage' to package.json according to the guide of https://docs.npmjs.com/cli/v8/configuring-npm/package-json
WRO-11514
Enact-DCO-1.0-Signed-off-by: SJ RO ([sj.ro@lge.com](mailto:sj.ro@lge.com))
=> WRO-11514: Add Repository/Hompage address to @enact/cli at npmjs.com

.travis.yml
Need to apply lint option ( max-warnings , report-unused-disable-directives) when building a PR.
Update .travis.yml to apply lint options
WRO-12570
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
=> WRO-12570: Update .travis.yml to apply lint options 

docs/building-apps.md
Fix wrong guide JSON should be CSS
WRO-12293
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>
=> WRO-12293: Fix wrong guide: from JSON to CSS

package.json
`@testing-library/user-event` v14 has been released and we need to update this module.
Updated `testing-library/user-event` to ^14.4.3
Unit tests based on `@testing-library/user-event`  v13 need to migrate to v14.
WRP-14328
=> WRP-14328: Update `@testing-library/user-event` to v14

README.md
Update README.md
Added CLI docs
Fixed build badge link
WRP-593
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>
=> WRP-593: Update README.md

.travis.yml
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
There was an error in the current node version, so it was temporarily fixed to 19.
However, since the error has disappeared since cli 6.0, the current node test is needed again.
Add the current node test.
WRP-16809
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
=> WRP-16809: Update .travis.yml to add current node test

CHANGELOG.md, commands/template.js
An error log was found in 'enact template --help'
_Expected result:_
>   Usage
>     enact template <action> ...
> 
>   Actions
>     enact template install [source] [name]
>     Install a template from a local or remote source
> 
>         source            Git URI, npm package or local directory
>                           (default: cwd)
>         name              Specific name for the template
> 
>     enact template link [directory] [name]
>     Symlink a directory into template management
> 
>         directory         Local directory path to link
>                           (default: cwd)
>         name              Specific name for the template
> 
>     enact template remove <name>
>     Remove a template …
=> WRQ-365: Fix enact template --help

CHANGELOG.md, commands/pack.js, docs/building-apps.md
The`--no-animation` pack option has merged as private API in #316 .
Now this option will be made as public.
- Made `--no-animation` public 
- Added documentation
WRQ-206
=> WRQ-206: Made `--no-animation` public and added documentation

npm-shrinkwrap.json, package.json
Update dependencies' minor and patch version
Update dependencies' minor and patch version
WRR-1519
=> WRR-1519: Update dependencies' minor and patch version

CHANGELOG.md, config/webpack.config.js, package.json
Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)
Support importing JSON files and generate css variables
Use postcss-import-json modules to import JSON files
WRR-29663
=> WRR-29663: Added support importing JSON files in CSS

npm-shrinkwrap.json, package.json
Update minor dependencies to fix vulnerabilities
Update minor dependencies to fix vulnerabilities
WRR-29513
=> WRR-29513: Update minor dependencies to fix vulnerabilities

config/webpack.config.js
Fixed design token path issue to read path properly in standalone app or in sampler(symlink case)
WRR-29663
=> WRR-29663: Fixed design token path issue
